name: Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests pandas numpy pytz matplotlib
    - name: Run Bot and Send Telegram Message
      env:
        TELEGRAM_TOKEN: "8341287362:AAF0hO6PMtcP5O2Y-sF34OffcN_zeLbIKNo"
        TELEGRAM_CHAT_ID: "-1003151787212"
      run: python bot.py
